version: "3"

services:
    nginx:
        image: nginx:1.13-alpine
        container_name: discord_notification_web
        labels:
            - "traefik.http.routers.discord-notification.rule=Host(`discord-notification.localhost`)"
        volumes:
            - ".:/application"
            - "./tools/docker/logs/nginx:/var/log/nginx"
            - "./tools/docker/nginx/site.conf:/etc/nginx/conf.d/default.conf"
        networks:
            traefik:
                ipv4_address: 172.16.20.1

    php:
        build: tools/docker/php8.2
        container_name: discord_notification_php
        volumes:
            - ".:/application"
        networks:
            traefik:
                ipv4_address: 172.16.20.2

    db:
        image: mysql:8.0
        container_name: discord_notification_db
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=discord_notification
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=dev
        networks:
            traefik:
                ipv4_address: 172.16.20.3

networks:
    traefik:
        external: true