name: Discord Notification
on: [push]
jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: deploy
        steps:
            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SERVER_HOST }}
                username: ${{ secrets.SERVER_LOGIN }}
                password: ${{ secrets.SERVER_PASS }}
                port: ${{ secrets.SERVER_PORT }}
                script: |
                  whoami
                  cd ${{secrets.SERVER_DIRECTORY}}
                  dep deploy
